### PR TITLE
Added the solution for dynamic array problem(hackerrank) in python

### PR DESCRIPTION
**Pull request by muskanapp**

### CODE REVIEW

**Comment by IndraAdhikary** [comment]
I am unable to find your file in the folder @muskanapp ?

**Comment by muskanapp** [comment]
Oh, but it's showing I have changed 1 file

**Comment by IndraAdhikary** [comment]
I still cannot locate the file @muskanapp ..... commit changes after you fork the original repo and then make a pull request. if you need any assistance, connect to me on discord of dsc iem. :)

**Comment by muskanapp** [comment]
I have created a new pull request. You can check that out!

**Pull request merged**
